
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from '@/app/component/header/page'
import "./globals.css";
import ThemeProvider from '@/app/context/page'
import ThemeWrapper from '@/app/component/ThemeWrapper'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vishal.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <ThemeProvider>
        <ThemeWrapper>
          <Header />
          <main>
            {children}
          </main>
        </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
